name: semcluster_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cudatoolkit=11.8.0
  - giflib=5.2.2
  - icu=70.1
  - jpeg=9e
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.5.2
  - libdeflate=1.13
  - libffi=3.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libiconv=1.17
  - libpng=1.6.38
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libzlib=1.2.12
  - lz4-c=1.9.4
  - lzo=2.10
  - ncurses=6.3
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - pip=25.3
  - python=3.9.12
  - readline=8.1.2
  - setuptools=80.9.0
  - sqlite=3.38.5
  - tesseract=5.2.0
  - tk=8.6.12
  - wheel=0.45.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==2.3.1
    - apted==1.0.3
    - astunparse==1.6.3
    - cachetools==6.2.2
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - click==8.1.8
    - flatbuffers==25.9.23
    - gast==0.4.0
    - gensim==4.4.0
    - google-auth==2.43.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.76.0
    - h5py==3.14.0
    - idna==3.11
    - importlib-metadata==8.7.0
    - jieba==0.42.1
    - joblib==1.5.2
    - keras==2.11.0
    - libclang==18.1.1
    - markdown==3.9
    - markupsafe==3.0.3
    - nltk==3.9.2
    - numpy==1.26.4
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cudnn-cu11==8.6.0.163
    - oauthlib==3.3.1
    - opencv-python==4.12.0.88
    - opt-einsum==3.4.0
    - packaging==25.0
    - pandas==2.3.3
    - pillow==11.3.0
    - protobuf==3.19.6
    - pyarrow==21.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pytesseract==0.3.13
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - regex==2025.11.3
    - requests==2.32.5
    - requests-oauthlib==2.0.0
    - rsa==4.9.1
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - six==1.17.0
    - smart-open==7.5.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==3.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.6.0
    - tqdm==4.67.1
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - urllib3==2.5.0
    - werkzeug==3.1.3
    - wrapt==2.0.1
    - zipp==3.23.0
prefix: /home/mhasan02/.conda/envs/semcluster_gpu

